import datetime
x=datetime.datetime.now()
print(x.strftime("%I"))
print(x.strftime("%a"))
print(x.strftime("%A"))
print(x.strftime("%d"))
print(x.strftime("%b"))
print(x.strftime("%B"))
print(x.strftime("%m"))
print(x.strftime("%y"))
print(x.strftime("%H"))
y=datetime.datetime(2024,6,12)
print(y.strftime("%I"))
print(y.strftime("%a"))
print(y.strftime("%A"))
print(y.strftime("%d"))
print(y.strftime("%b"))
print(y.strftime("%B"))
print(y.strftime("%m"))
print(y.strftime("%y"))

a=[1,2,3,4]
print(a)
print(type(a))
print(len(a))
x=frozenset(a)
print(x)