import os
# a=open("sample.txt","r")
# print(a.read())
# print(a.read(3))
# print(a.readline())
# print(a.readline())
# a.close()
# x=open("sample.txt","a")
# x.write("appu mandan")
# x.close()
# x=open("sample.txt","r")
# print(x.read())
# x.close()
# x=open("sample.txt","w")
# x.write("apple ball cat dog")
# x.close()
# x=open("sample.txt","r")
# print(x.read())
# x.close()
# b=open("sample3.txt","x")
# os.remove("sample3.txt")
os.rmdir("simple")