# x=open("helo1.txt","w")
# x.write("hello world")
# x.close()
# x=open("helo2.txt","w")
# x.write("good morning")
# x.close()
q=open("helo1.txt","r")
m=q.read()
print(m)
# h=open("hi3.txt","x")
# h.close()
h=open("hi3.txt","w")
h.write(m)
h.close()
q=open("helo2.txt","r")
n=q.read()
print(n)
h=open("hi3.txt","a")
h.write(n)
h.close()

