# a=open("tsk1.txt","x")
# a.close()
# a=open("tsk1.txt","w")
# a.write("good morning all")
# a.close()
a=open("tsk1.txt","r")
print(a.read())
print(a.read(5))
print(a.readline())
a.close()
a=open("tsk1.txt","a")
a.write("how are uh")
a.close()